version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./db/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: miniProj

  postgres:
    image: postgres
    restart: always
    container_name: pg
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_pg.sql:/docker-entrypoint-initdb.d/init_pg.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_DB: miniProj

